### ISSUE TITLE
sd.ascii documented but not present in the code

### ISSUE THREAD

**Issue by grempe** [weisrc/sirdez#1]
Hi,

The documented `sd.ascii` encoding does not seem to actually exist in the code.

https://github.com/weisrc/sirdez/search?q=ascii

**Comment by weisrc** [comment]
Hello!, the documentation is slightly outdated. ASCII is now latin1, since it is the name used by NodeJS. I will update the docs ASAP. Thank you for raising the first issue!

**Comment by weisrc** [comment]
I just updated the docs. If you want to see the code, please visit https://github.com/weisrc/sirdez/blob/main/src/encodings/latin1.ts for the browser implementation and https://github.com/weisrc/sirdez/blob/main/src/node_encodings/latin1.ts for the node implementation which is slightly faster in node. I will be closing this issue.
