### ISSUE TITLE
Calling 'fromBytes' after calling 'toBytes' returns tainted data

### ISSUE THREAD

**Issue by grempe** [weisrc/sirdez#2]
I'm trying to understand a strange behavior I observed. I ran into this when I started seeing ghost data show up in my application. 

It would seem to me that calling `toBytes` with an empty `Uint8Array` should always return the same result no matter what previously happened with `fromBytes`.

Here's a sample.

```typescript
import * as sd from "sirdez"

const test = sd.use(
  sd.struct({
    foo: sd.string(sd.utf8js, sd.uint8),
  })
)

const objOne = test.fromBytes(new Uint8Array())
console.log(objOne) // -> { foo: '' }

// this taints future calls to fromBytes()
const arrOne = test.toBytes({ foo: "bar" })
console.log(arrOne)

// Why is this returning { foo: 'bar' } and not { foo: '' }
// It seems that the call to toBytes leaves some state hanging around?
const objTwo = test.fromBytes(new Uint8Array())
console.log(objTwo) // -> { foo: 'bar' } 
```

**Comment by weisrc** [comment]
Without any testing on it on this issue specifically. My guess is that sending an empty byte array is an invalid input because the smallest length it supports is 1 due to the  foo field which requires a uint8 for the length of the string. So passing a byte array with a single 0 in it should fix it. I should make it throw errors, but having extra if conditions slows it down. I will investigate further.

**Comment by grempe** [comment]
FYI, replacing the `new Uint8Array()` with `new Uint8Array([0, 1])` returns `{ foo: '' }` for both `objOne` and `objTwo`.

Intuitively though, I would expect `fromBytes` to throw an error if there are not enough bytes present to fulfill the requirements of the `test` struct. Otherwise too short (or too long?) bytes coming in will result in indeterminate output. No?

**Comment by weisrc** [comment]
Yes, I think I can make it throw an error with a single IF statement both for serialize and deserialize. The fix should be live by the end of today EST.

**Comment by weisrc** [comment]
Actually it is only deserialize.

**Comment by weisrc** [comment]
Implemented https://github.com/weisrc/sirdez/commit/ba054e0d24f52bff0c7e2e50e71b7e43fd52c963, will soon publish.

**Comment by weisrc** [comment]
v0.0.5 is now live and contains the patch!

**Comment by grempe** [comment]
Super. I will check it out. Thanks for the extremely quick response. I'll let you know if I see anything unusual.

Cheers.

**Comment by weisrc** [comment]
Thought, I just realized that if the input is too long, it will ignore the extra bytes. Is this fine by you? However, for the too short case, it will throw a range error, and therefore, deterministic serialized output or range error are the only outputs. Please note that the range error message can either be empty (thrown by the library) or have the regular dataview out of bounds error.

**Comment by weisrc** [comment]
I created a new branch with: it will be ready to merge if you are interested in it. https://github.com/weisrc/sirdez/tree/throw-too-long

**Comment by grempe** [comment]
I think a too long error would be helpful.

My use case is to encode a struct with info into a unique ID. I base58 encode those bytes into the ID string.

So it would be nice to know that a Uint8Array is too short/long for my specific sirdez struct. I would not want to try to process a 1Mb ID for example. 

I'm not sure how sirdez can know what is too long/short though. Is it just that it is outside the boundary of a uint8 string length?

Concrete examples of what would pass/fail, and documentation of that would be helpful.

**Comment by weisrc** [comment]
It actually doesn't know ahead of time if it is too long or too short, it is really at the end of the process that it determines it.

**Comment by grempe** [comment]
> It actually doesn't know ahead of time if it is too long or too short, it is really at the end of the process that it determines it.

That's OK.  I do length checking on incoming ID's anyway and I'd reject anything obviously too long.

But if there is no major impact, then my inclination would be to check for both long and short and reject anything that would not be 'valid'.

I don't know enough about the internals though to understand yet what would cause those issues in practice. Eliminating developer surprise at odd results though seems worth the extra if statements if that is what will result.

**Comment by weisrc** [comment]
I think only having a too long and too short error is enough since given something too long, for example 1Mb, and a schema requiring only a few bytes, sirdez will ignore the extra bytes. With the current version on main, it will successfully serialize it and then do a check to see if the state machine's cursor and input buffer length matches, if not it will throw a range error.

**Comment by weisrc** [comment]
Done f213bf4f859a7cfb3fea898f5c6af786c57979d7

**Comment by grempe** [comment]
Cool.  The new docs are helpful.

When you cut a release I'll pull it in. I'm working on my end now. :-)
