### ISSUE TITLE
Improve documentation for `noeval`.

### ISSUE THREAD

**Issue by grempe** [weisrc/sirdez#5]
I ran into a problem with sirdez when trying to run it in the context of a Cloudflare Worker.

Workers (and probably most serverless environments) do not allow `eval` or `new Function` calls.

https://github.com/cloudflare/wrangler/issues/1268

Once I narrowed the problem down to sirdez (which I could only see in the worker dev environment, not from production logs) I was pleased to see there was a `noeval` option.

It took some digging around and experimentation though to figure out how to actually use it.

Having a section of the README dedicated to this would be helpful. Or bring it more up front in the docs.

Note also that Socket.dev calls out sirdez with a warning since it uses `new Function`.

https://socket.dev/npm/package/sirdez/overview/0.0.6

You might think about having the default be to use the `noeval` version and let people opt-in to the more unsafe behavior.

You mentioned in the docs that there is a performance hit when using `noeval` structs.

https://weisrc.github.io/sirdez/data_types/struct.html#variants

> much slower because it is implemented using a for loop

I tried to follow the link on the README to `Performance Results` to better understand the impact but its a broken link.

https://github.com/weisrc/sirdez/blob/main/TODO

**Comment by weisrc** [comment]
Thank you for bringing this up to me, I have added a new feature to the README feature list thanks to you :)

https://github.com/weisrc/sirdez/commit/f9bfa7c33eabe07a605c6fd7a36fafe3b992ebef

As for the performance link, I will handle that when I find time. I will keep this issue open as a reminder to do so. 

Any suggestions on what is the most intuitive way to display the performance benchmarks?

**Comment by weisrc** [comment]
I have added this page with all the benchmark results: https://weisrc.github.io/sirdez/performance.html
