### ISSUE TITLE
Question: differentiating between different types

### ISSUE THREAD

**Issue by pecnik** [weisrc/sirdez#6]
Is there a recommended approach to differentiating different structs?

Currently I define a type as the first prop in every struct.
And then check the first value in the encoded bytes.
So far it works fine, but I don't know if it's a good idea.

````ts
const Foo = sd.use(
    sd.struct({
        type: sd.uint8,
        foo: sd.uint8,
        // ...
    }),
);

const Bar = sd.use(
    sd.struct({
        type: sd.uint8,
        bar: sd.uint8,
        // ...
    }),
);

// ...

switch (bytes[0]) {
    case Type.Bar:
        const bar = Bar.fromBytes(bytes);
        break;

    case Type.Foo:
        const foo = Foo.fromBytes(bytes);
        break;

    default:
        break;
}

````

p.s: thank you for this library, took me forever to find it, but i'm so glad I did

**Comment by weisrc** [comment]
Hello,

The method is good. I would have never thought of it. However, for more complicated data types, I suggest you creating your own serializer/deserializer via https://weisrc.github.io/sirdez/extending.html#data-type. I can't figure out a good way to do this using a simple function that is generic enough for most use cases, when I do, I will add this function to the library. If you have any suggestions, please do tell me.

My pleasure! No problem! And I thank you too for using it!
